routes/web.php
<?php

use App\Http\Controllers\api\GatewayApiController;
use App\Http\Controllers\CbuController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ClienteController;
use App\Http\Controllers\ComentarioClienteController;
use App\Http\Controllers\ConsultaController;
use App\Http\Controllers\CuentaCorrienteController;
use App\Http\Controllers\ExpensaController;
use App\Http\Controllers\GatewayController;
use App\Http\Controllers\HotelController;
use App\Http\Controllers\ImputarController;
use App\Http\Controllers\ParametroController;
use App\Http\Controllers\ReciboController;
use App\Http\Controllers\SemanaUsoController;
use App\Http\Controllers\TemporadaController;
use App\Http\Controllers\UnidadController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();
Route::get('cliente/reset/{token}', [ClienteController::class, 'resetPasswordForm'])->name('cliente.reset.get');
Route::put('cliente/reset/{cliente}', [ClienteController::class, 'resetPassword'])->name('cliente.reset.update');
Route::get('recibos/pdf/{recibo}', [ReciboController::class, 'getReciboPdf'])->name('recibos.pdf');
Route::get('recibos/pdf/{recibo}/export', [ReciboController::class, 'getPdfExportRecibo'])->name('recibos.pdf.export');
Route::get('hotel/calendario/{hotel}', [HotelController::class, 'getCalendario'])->name('hotel.calendario');

Route::middleware(['auth'])->group(function () {
	Route::get('cliente/saldo/especifico', [ClienteController::class, 'getClienteComposicionSaldoTodo'])->name('cliente.saldo.compuesto.todos');
	Route::get('cliente/saldo/composicion/{clienteId}', [ClienteController::class, 'getClienteComposicionSaldo'])->name('cliente.saldo.compuesto');
	Route::get('cliente/exportar/excel/{filter?}', [ClienteController::class ,'exportClientesExcel'])->name('cliente.exportar.contratos');
	Route::resource('cliente', ClienteController::class);

	Route::resource('temporada', TemporadaController::class);

	Route::resource('hotel', HotelController::class);

	Route::resource('unidad', UnidadController::class);

	Route::resource('consultas', ConsultaController::class);

	Route::resource('recibos', ReciboController::class);
	Route::get('recibo/export', [ReciboController::class, 'getReciboExport'])->name('recibos.export');

	Route::get('expensas/choose', [ExpensaController::class, 'chooseTempAndHotel'])->name('expensas.choose');
	Route::post('expensas/unidad', [ExpensaController::class, 'createPricesToUnidad'])->name('expensas.unidad');
	Route::get('expensas/clientes/{temporada}/{anio}/{fecha}/{fecha_vencimiento}', [ExpensaController::class, 'generateExpensas'])->name('expensas.clientes');
	Route::resource('expensas', ExpensaController::class);
	Route::get('expensas/unica/cliente', [ExpensaController::class, 'createUniqueExpensa'])->name('expensa.unica');
	Route::post('expensas/unica/cliente', [ExpensaController::class, 'createUniqueExpensaStore'])->name('expensa.unica.store');

	Route::get('usos/excel/download', [SemanaUsoController::class, 'exportToExcel'])->name('usos.excel.download');
	Route::resource('usos', SemanaUsoController::class);

	Route::get('saldo/cliente', [ClienteController::class, 'getSaldoclientes'])->name('cliente.saldo');
	Route::get('saldo/cliente/export', [ClienteController::class, 'getExcelSaldoclientes'])->name('cliente.saldo.export');

	Route::get('comentario/cliente/{cliente}', [ComentarioClienteController::class, 'create'])->name('comentario.create');
	Route::post('comentario/cliente/create', [ComentarioClienteController::class, 'store'])->name('comentario.store');
	Route::get('comentario/cliente/{comentario}/{cliente}', [ComentarioClienteController::class, 'edit'])->name('comentario.edit');
	Route::put('comentario/cliente/update/{comentario}/{cliente}', [ComentarioClienteController::class, 'update'])->name('comentario.update');
	Route::delete('comentario/cliente/delete/{comentario}', [ComentarioClienteController::class, 'destroy'] )->name('comentario.destroy');

	Route::resource('parametros', ParametroController::class);

	Route::resource('gateway', GatewayController::class);

	Route::resource('cbu', CbuController::class);

	Route::resource('CuentaCorriente', CuentaCorrienteController::class);

	Route::get('imputar/cliente/{clienteId}', [ImputarController::class, 'imputarAutomatico'])->name('imputar.cliente');
	Route::get('imputar/desimputar/pago/{idImputacion}', [ImputarController::class, 'desimputador'])->name('desimputar.pago');
	Route::get('imputar/lista/cliente/{cliente}', [ImputarController::class, 'imputarIndividual'])->name('imputar.cliente.recibos');
	Route::get('imputar/todo', [ImputarController::class, 'imputarTodo'])->name('imputar.todo');

	Route::get('credicard/{id}', [GatewayApiController::class, 'show']);
});
Route::get('/', [App\Http\Controllers\HomeController::class, 'index']);

app/Models/Cliente.php
<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Kyslik\ColumnSortable\Sortable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Support\Facades\DB;

class Cliente extends Model
{
	use HasFactory, Sortable, Notifiable;
	protected $table = 'clientes_con_saldo',
		$fillable = [
			'identificacion', 'nombre', 'apellido', 'telefono', 'celular',
			'email', 'nombre_conyugue', 'apellido_conyugue', 'celular_conyugue',
			'email_conyugue', 'password', 'hotel',
			'dni', 'dni_conyugue', 'fecha_nacimiento', 'fecha_naciemiento_conyugue',
			'domicilio', 'localidad', 'provincia', 'pais', 'cod_postal',
			'email2', 'id_rci', 'id_interval', 'telefono_laboral','saldo', 'dias_mora', 'saldo_vencido', 'cuil'
		],
		$sortable  = [
			'identificacion', 'nombre', 'apellido', 'telefono', 'celular',
			'email', 'nombre_conyugue', 'apellido_conyugue', 'celular_conyugue',
			'email_conyugue', 'password', 'hotel',
			'dni', 'dni_conyugue', 'fecha_nacimiento', 'fecha_naciemiento_conyugue',
			'domicilio', 'localidad', 'provincia', 'pais', 'cod_postal',
			'email2', 'id_rci', 'id_interval', 'telefono_laboral','saldo', 'dias_mora', 'saldo_vencido', 'cuil'
		];
	public $timestamps = false;


	public function hotelR()
	{
		return $this->belongsTo(Hotel::class, 'hotel', 'id');
	}
	public function unidades()
	{
		return $this->belongsToMany(Unidad::class, 'unidades_por_cliente', 'cliente', 'unidad', 'id', 'id')
		->withPivot(['temporada']);
	}
	public function consultas(){
		return $this->hasMany(Consulta::class, 'cliente_id', 'id');
	}
	public function cuentasCorrientes(){
		return $this->hasMany(CuentaCorriente::class)->orderBy('created_at', 'desc');
	}
	public function recibos(){
		return $this->hasMany(Recibo::class);
	}

	/* accesors */
	public function getFullNameAttribute(){
		return $this->nombre.' '.$this->apellido;
	}
	public function clienteMultiple(){
		return $this->hasOne(Cliente::class,'email', 'email')->where('id', '!=', $this->id);
	}
	public function getFullCuentaCorrientesAttribute(){
		$collection = new Collection($this->cuentasCorrientes);
		if ($this->clienteMultiple && !$this->clienteMultiple->cuentasCorrientes->isEmpty()) {
			# code...monibea2015@gmail.com aleovio@gmail.com
			$collection = $collection->merge($this->clienteMultiple->cuentasCorrientes);
		}
		return $collection;
	}
	public function getFullRecibosAttribute(){
		$collection =  collect($this->recibos);
		if ($this->clienteMultiple) {
			# code...monibea2015@gmail.com
			$collection->merge($this->clienteMultiple->recibos);
		}
		return $collection;
	}


	public function usos(){
		return $this->hasMany(SemanaUso::class);
	}
	public function tokens(){
		return $this->hasMany(TokenCliente::class);
	}

	public function comentarios(){
		return $this->hasMany(ComentarioCliente::class);
	}
	/* public function routeNotificationForMail($notification){
		return env('MAIL_ADMIN', 'gorge2004@gmail.com') ;
	} */
	public function getCcStoreAttribute(){
		$now = Carbon::now();
		$now->setTime(0,0);
		$now->addYears(10);
		$now =  $now->format('Y-m-d');
		return DB::select("CALL consultar_imputaciones( $this->id,'1900-01-01', '$now')") ;
	}
}

resources/views/comentario/index.blade.php
@extends('layouts.layout')
@section('title', 'Cliente')
@section('content')
    @if ($message = Session::get('success'))
        <div class="row justify-content-center">
            <div class=" col-6  mt-2 alert alert-success">
                <p>{{ $message }}</p>
            </div>
        </div>
    @endif
    <div class="row h-120-px align-items-center justify-content-between">
		<div class="col p-0 d-flex align-items-center gap-title">
			<i class="fas fa-user-circle fa-3x" style="color: #e8a02f !important; "></i>
			<h1 class="title-clubinn"> Cliente</h1>
		</div>
		<div class="col-8 col-xl-2 p-0 d-flex justify-content-end">
			<a href="{{ route('cliente.create') }}" type="button"
				class="btn btn-block btn-clubinn-blue clubinn-blue-color"> Crear Cliente</a>
		</div>
    </div>
    <div class="row ">
        <div class="col-12 p-0 table-responsive">
            @if ($clientes->isEmpty())
                <p class="lead">No existen clientes.</p>
            @else
                <table class="table table-bordered table-clubinn">
                    <thead>
                        <th scope="col" class="text-nowrap">@sortablelink('identificacion', 'Identificación', [],  ['class' => ' clubinn-th-text'])</th>
                        <th scope="col" class="text-nowrap">@sortablelink('nombre', 'Nombre', [],  ['class' => ' clubinn-th-text'])</th>
                        <th scope="col" class="text-nowrap">@sortablelink('apellido', 'Apellido', [],  ['class' => ' clubinn-th-text'])</th>
                        <th scope="col" class="text-nowrap">@sortablelink('celular', 'Celular', [],  ['class' => ' clubinn-th-text'])</th>
                        <th scope="col" class="text-nowrap">@sortablelink('email', 'Email', [],  ['class' => ' clubinn-th-text'])</th>
                        <th scope="col" class="text-nowrap">@sortablelink('hotel', 'Hotel', [],  ['class' => ' clubinn-th-text'])</th>
                        <th scope="col" class="text-nowrap"></th>
                    </thead>
                    <tbody>
                        @foreach ($clientes as $cliente)
                            <tr>
                                <td >{{ $cliente->identificacion }} </td>
                                <td >{{ $cliente->nombre }}</td>
                                <td >{{ $cliente->apellido }}</td>
                                <td >{{ $cliente->celular }}</td>
                                <td >{{ $cliente->email }}</td>
                                <td >{{ $cliente->hotelR->nombre }}</td>

                                <td style="
								min-width: 100px;
							">
                                    @can('cliente-edit')
                                        <a href="{{ route('cliente.edit', $cliente->id) }}" type="button"
                                            class="btn btn-outline-primary btn-sm  my-1"> <i class="fas fa-edit"></i></a>
                                    @endcan
                                    @can('cliente-list')

										<a href="{{ route('cliente.show', $cliente->id)}}" class="btn btn-outline-success btn-sm" disabled><i
												class="far fa-eye"></i></a>
                                    @endcan

                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>

            @endif
            {{ method_exists($clientes, 'appends') ? $clientes->appends(\Request::except('page'))->render() : '' }}

        </div>
    </div>
@endsection

resources/views/comentario/show.blade.php
@extends('layouts.layout')
@section('title', 'Cliente')
@section('content')

    <div class="row h-120-px align-items-center justify-content-between">
        <div class="col p-0 d-flex align-items-center gap-title">
            <i class="fas fa-user-circle fa-3x" style="color: #e8a02f !important; "></i>
            <h1 class="title-clubinn">
				{{ $cliente->full_name }}
				<small style="display: block">{{ $cliente->email}}</small>
			</h1>
        </div>
    </div>

    <div class="row">
        <div class="col-12">
            <ul class="nav nav-tabs" id="myTab" role="tablist">
                <li class="nav-item" role="presentation">
                    <a class="nav-link active" id="unidad-tab" data-toggle="tab" href="#unidad" role="tab"
                        aria-controls="unidad" aria-selected="true">Unidades</a>
                </li>
                <li class="nav-item" role="presentation">
                    <a class="nav-link" id="usos-tab" data-toggle="tab" href="#usos" role="tab" aria-controls="profile"
                        aria-selected="false">Usos</a>
                </li>
                <li class="nav-item" role="presentation">
                    <a class="nav-link" id="contact-tab" data-toggle="tab" href="#recibos" role="tab"
                        aria-controls="contact" aria-selected="false">Recibos</a>
                </li>
				<li class="nav-item" role="presentation">
                    <a class="nav-link" id="cuenta-tab" data-toggle="tab" href="#cuenta" role="tab"
                        aria-controls="cuenta" aria-selected="false">Cuenta corriente</a>
                </li>
				<li class="nav-item" role="presentation">
                    <a class="nav-link" id="comentario-tab" data-toggle="tab" href="#comentarios" role="tab"
                        aria-controls="comentario" aria-selected="false">Comentarios</a>
                </li>
            </ul>
            <div class="tab-content" id="myTabContent">
                <div class="tab-pane fade show active" id="unidad" role="tabpanel" aria-labelledby="unidad-tab">
                    <div class="col-12  p-0 table-responsive">
                        @if ($cliente->unidades->isEmpty())
                            <p class="lead">No existen unidades.</p>
                        @else
                            <table class="table table-bordered table-clubinn">
                                <thead>
                                    <th scope="col" class="text-nowrap clubinn-th-text">Nombre</th>
                                    <th scope="col" class="text-nowrap clubinn-th-text">Capacidad</th>
                                    <th scope="col" class="text-nowrap clubinn-th-text">Capacidad maxima</th>
                                    <th scope="col" class="text-nowrap clubinn-th-text">Temporada</th>
                                    <th scope="col" class="text-nowrap clubinn-th-text">Hotel</th>
                                </thead>
                                <tbody>
                                    @foreach ($cliente->unidades as $unidad)
                                        <tr>
                                            <td class="text-gergal-color">{{ $unidad->nombre }}</td>
                                            <td class="text-gergal-color">{{ $unidad->capacidad }}</td>
                                            <td class="text-gergal-color">{{ $unidad->capacidad_maxima }}</td>
                                            <td class="text-gergal-color">{{ $temporadas->firstWhere('id', $unidad->pivot->temporada)->nombre  }}</td>
                                            <td class="text-gergal-color">{{ $unidad->hotelR->nombre }}</td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>

                        @endif
                    </div>
                </div>
                <div class="tab-pane fade" id="usos" role="tabpanel" aria-labelledby="usos-tab">
                    <div class="col-12  p-0 table-responsive">
                        @if ($cliente->usos->isEmpty())
                            <p class="lead">No existen Semana de Usos.</p>
                        @else
                            <table class="table table-bordered table-clubinn">
                                <thead>
                                    <th scope="col" class="text-nowrap clubinn-th-text">Unidad</th>
                                    <th scope="col" class="text-nowrap clubinn-th-text">Cliente</th>
                                    <th scope="col" class="text-nowrap clubinn-th-text">Estado</th>
                                    <th scope="col" class="text-nowrap clubinn-th-text">Fecha de vencimiento</th>
                                    <th scope="col" class="text-nowrap clubinn-th-text">Año</th>
                                    <th scope="col" class="text-nowrap clubinn-th-text">Dias</th>
                                    <th scope="col" class="text-nowrap clubinn-th-text">Semana</th>
                                    <th scope="col" class="text-nowrap clubinn-th-text">Temporada</th>
                                    <th scope="col" class="text-nowrap clubinn-th-text">Hotel</th>
                                    <th scope="col" class="text-nowrap clubinn-th-text"></th>
                                </thead>
                                <tbody>
                                    @foreach ($cliente->usos as $uso)
                                        <tr>

                                            <td class="text-gergal-color">
                                                {{ $uso->unidad->unidadR->nombre }}</td>
                                            <td class="text-gergal-color">{{ $uso->cliente->full_name }}</td>
                                            <td class="text-gergal-color">{{ $uso->estado->nombre }}</td>
                                            <td class="text-gergal-color">{{ $uso->fecha_vencimiento->format('d/m/Y') }}
                                            </td>
                                            <td class="text-gergal-color">{{ $uso->anio }}</td>
                                            <td class="text-gergal-color">{{ $uso->dia }}</td>
                                            <td class="text-gergal-color">{{ $uso->semana }}</td>
                                            <td class="text-gergal-color">{{ $uso->temporada->nombre }}</td>
                                            <td class="text-gergal-color">{{ $uso->temporada->hotelR->nombre }}</td>
                                            <td style="min-width: 100px;">
                                                @if ($uso->estado->nombre == 'Solicitado')
                                                    <form style="display: inline-block;"
                                                        action="{{ route('usos.update', $uso->id) }}" method="POST">
                                                        @csrf
                                                        @method('PUT')
                                                        <button type="button"
                                                            class="btn btn-outline-primary btn-sm  my-1 btn-confirmar">Confirmar</button>
                                                    </form>
                                                @endif
                                                @can('uso-edit')
                                                @endcan
                                                @can('uso-delete')
                                                    <form style="display: inline-block;" name="form-delete"
                                                        action="{{ route('usos.destroy', $uso->id) }}" method="POST">
                                                        @csrf
                                                        @method('DELETE')
                                                        <button type="submit" class="btn btn-outline-danger btn-sm" disabled><i
                                                                class="fas fa-trash-alt"></i></button>
                                                    </form>
                                                @endcan

                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>

                        @endif

                    </div>
                </div>
                <div class="tab-pane fade" id="recibos" role="tabpanel" aria-labelledby="contact-tab">
					<div class="row">
						<div class="col-12  p-0 table-responsive">
							@if ($cliente->recibos->isEmpty())
								<p class="lead">No existen recibos cargado.</p>
							@else
								<table class="table table-bordered table-clubinn">
									<thead>
										<th scope="col" class="text-nowrap">@sortablelink('fecha_pago', 'Fecha', [], ['class' => '
											clubinn-th-text'])</th>
										<th scope="col" class="text-nowrap">@sortablelink('cliente.nombre', 'Cliente', [], ['class' => '
											clubinn-th-text'])</th>
										<th scope="col" class="text-nowrap">@sortablelink('importe', 'Importe', [], ['class' => '
											clubinn-th-text'])</th>
										<th scope="col" class="text-nowrap">@sortablelink('estado.nombre', 'Estado', [], ['class' => '
											clubinn-th-text'])</th>
										<th scope="col" class="text-nowrap"></th>
									</thead>
									<tbody>
										@php
											$classToStatus = ['Pendiente' => 'bg-warning', 'Aceptado' => 'bg-success', 'Anulado' => 'bg-danger'];

										@endphp
										@foreach ($cliente->recibos as $recibo)
											<tr class="{{ $classToStatus[$recibo->estado->nombre] }}">
												<td class="text-gergal-color text-white">{{ $recibo->fecha_pago->format('d/m/Y') }}</td>
												<td class="text-gergal-color text-white">{{ $recibo->cliente->full_name }}</td>
												<td class="text-gergal-color text-white">{{ $recibo->importe . ' $' }}</td>
												<td class="text-gergal-color text-white">{{ $recibo->estado->nombre }}</td>

												<td>
													<form name="formSubmit" class="form-confirm" style="display: inline-block;"
														action="{{ route('recibos.update', $recibo->id) }}" method="POST">
														@csrf
														@method('PUT')


														<button type="submit" class="btn btn-outline-primary btn-sm  my-1  btn-confirm"
															name="btnConfirmar">Confirmar</button>
													</form>

													@if ($recibo->estado->nombre == 'Pendiente')

													@endif
													@can('recibo-edit')
														<a href="{{ route('recibos.edit', $recibo->id) }}" type="button"
															class="btn btn-outline-primary btn-sm  my-1"> <i class="fas fa-edit"></i></a>
													@endcan


												</td>
											</tr>
										@endforeach
									</tbody>
								</table>

							@endif

						</div>
					</div>
				</div>
				<div class="tab-pane fade" id="cuenta" role="tabpanel" aria-labelledby="cuenta-tab">
					<div class="row">
						<div class="col-12  p-0 table-responsive">
							@if ($cliente->full_cuenta_corrientes->isEmpty())
								<p class="lead">No existen registro de cuenta corriente cargado.</p>
							@else
								<table class="table table-bordered table-clubinn">
									<thead>
										<th scope="col" class="text-nowrap clubinn-th-text">fecha</th>
										<th scope="col" class="text-nowrap">Fecha vencimiento</th>
										<th scope="col" class="text-nowrap">Importe</th>
										<th scope="col" class="text-nowrap">Tipo de movimiento</th>

									</thead>
									<tbody>
										@foreach ($cliente->full_cuenta_corrientes as $cc)
											<tr >
												<td class="text-gergal-color text-white">{{ $cc->fecha }}</td>
												<td class="text-gergal-color text-white">{{ $cc->fecha_vencimiento }}</td>
												<td class="text-gergal-color text-white">{{ $cc->importe * $cc->movimiento->signo . ' $' }}</td>
												<td class="text-gergal-color text-white">{{ $cc->movimiento->nombre }}</td>


											</tr>
										@endforeach
									</tbody>
								</table>

							@endif

						</div>
					</div>
				</div>
				<div class="tab-pane fade" id="comentarios" role="tabpanel" aria-labelledby="comentario-tab">
					@include('cliente.comentarios-table')

				</div>
            </div>
        </div>

    </div>

    <script type="text/javascript">
        window.onload = function() {

            const butonnsConfirmar = document.querySelectorAll('.btn-confirmar');
            for (const confirmar of butonnsConfirmar) {
                confirmar.addEventListener('click', handlerConfirmarButton);
            }

            function handlerConfirmarButton(evt) {
                if (!confirm('Desea confirmar esta solicitud de uso ?')) {
                    evt.preventDefault();
                }
                evt.submit();
            }
        }
    </script>
@endsection

resources/views/comentario/store.blade.php
@extends('partials.form.form')

@section('form-title', 'Comentario')
@section('form-route', route('comentario.store'))
@section('form-content')
    <div class="form-group row">
        <div class="col-md-12 px-5">
			<input type="hidden" name="cliente_id" value="{{ $cliente->id}}" >
            <input  type="text"
                class="form-control @error('cliente_id') is-invalid @enderror"
                value="{{ $cliente->full_name }}" disabled>
            @error('cliente_id')
                <span class="invalid-feedback" style="background-color: red;
                                       color: white;
                                       margin-top: 0;" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
            @enderror
        </div>
    </div>
    <div class="form-group row">
        <div class="col-md-12 px-5">
			<label for="observacion">Comentario sobre el cliente</label>

			<textarea  class="form-control @error('observacion') is-invalid @enderror" id="observacion" name="observacion"></textarea>
            @error('observacion')
                <span class="invalid-feedback" style="background-color: red;
                                        color: white;
                                        margin-top: 0;" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
            @enderror
        </div>
    </div>


    <div class="form-group row mb-5">
        <div class="col-md-8 offset-4">
            <button type="submit" class="btn btn-success">
                Crear
            </button>
        </div>
    </div>
@endsection

resources/views/comentario/update.blade.php
@extends('partials.form.form')

@section('form-title', 'Cliente')
@section('form-route', route('comentario.update', ['comentario' => $comentario->id, 'cliente' => $cliente->id]))
@section('form-content')
    @method('PUT')
    <div class="form-group row">
        <div class="col-md-12 px-5">
            <input type="hidden" name="cliente_id" value="{{ $cliente->id }}">
            <input type="text" class="form-control @error('cliente_id') is-invalid @enderror"
                value="{{ $cliente->full_name }}" disabled>
            @error('cliente_id')
                <span class="invalid-feedback" style="background-color: red;
                                               color: white;
                                               margin-top: 0;" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
            @enderror
        </div>
    </div>
    <div class="form-group row">
        <div class="col-md-12 px-5">
            <label for="observacion">Comentario sobre el cliente</label>

            <textarea class="form-control @error('observacion') is-invalid @enderror" id="observacion"
                name="observacion">{{$comentario->observacion}}</textarea>
            @error('observacion')
                <span class="invalid-feedback" style="background-color: red;
                                                color: white;
                                                margin-top: 0;" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
            @enderror
        </div>
    </div>

    <div class="form-group row mb-5">
        <div class="col-md-8 offset-4">
            <button type="submit" class="btn btn-success">
                Actualizar comentario
            </button>
        </div>
    </div>
@endsection