routes/web.php
<?php

use App\Http\Controllers\api\GatewayApiController;
use App\Http\Controllers\CbuController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ClienteController;
use App\Http\Controllers\ComentarioClienteController;
use App\Http\Controllers\ConsultaController;
use App\Http\Controllers\CuentaCorrienteController;
use App\Http\Controllers\ExpensaController;
use App\Http\Controllers\GatewayController;
use App\Http\Controllers\HotelController;
use App\Http\Controllers\ImputarController;
use App\Http\Controllers\ParametroController;
use App\Http\Controllers\ReciboController;
use App\Http\Controllers\SemanaUsoController;
use App\Http\Controllers\TemporadaController;
use App\Http\Controllers\UnidadController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();
Route::get('cliente/reset/{token}', [ClienteController::class, 'resetPasswordForm'])->name('cliente.reset.get');
Route::put('cliente/reset/{cliente}', [ClienteController::class, 'resetPassword'])->name('cliente.reset.update');
Route::get('recibos/pdf/{recibo}', [ReciboController::class, 'getReciboPdf'])->name('recibos.pdf');
Route::get('recibos/pdf/{recibo}/export', [ReciboController::class, 'getPdfExportRecibo'])->name('recibos.pdf.export');
Route::get('hotel/calendario/{hotel}', [HotelController::class, 'getCalendario'])->name('hotel.calendario');

Route::middleware(['auth'])->group(function () {
	Route::get('cliente/saldo/especifico', [ClienteController::class, 'getClienteComposicionSaldoTodo'])->name('cliente.saldo.compuesto.todos');
	Route::get('cliente/saldo/composicion/{clienteId}', [ClienteController::class, 'getClienteComposicionSaldo'])->name('cliente.saldo.compuesto');
	Route::get('cliente/exportar/excel/{filter?}', [ClienteController::class ,'exportClientesExcel'])->name('cliente.exportar.contratos');
	Route::resource('cliente', ClienteController::class);

	Route::resource('temporada', TemporadaController::class);

	Route::resource('hotel', HotelController::class);

	Route::resource('unidad', UnidadController::class);

	Route::resource('consultas', ConsultaController::class);

	Route::resource('recibos', ReciboController::class);
	Route::get('recibo/export', [ReciboController::class, 'getReciboExport'])->name('recibos.export');

	Route::get('expensas/choose', [ExpensaController::class, 'chooseTempAndHotel'])->name('expensas.choose');
	Route::post('expensas/unidad', [ExpensaController::class, 'createPricesToUnidad'])->name('expensas.unidad');
	Route::get('expensas/clientes/{temporada}/{anio}/{fecha}/{fecha_vencimiento}', [ExpensaController::class, 'generateExpensas'])->name('expensas.clientes');
	Route::resource('expensas', ExpensaController::class);
	Route::get('expensas/unica/cliente', [ExpensaController::class, 'createUniqueExpensa'])->name('expensa.unica');
	Route::post('expensas/unica/cliente', [ExpensaController::class, 'createUniqueExpensaStore'])->name('expensa.unica.store');

	Route::get('usos/excel/download', [SemanaUsoController::class, 'exportToExcel'])->name('usos.excel.download');
	Route::resource('usos', SemanaUsoController::class);

	Route::get('saldo/cliente', [ClienteController::class, 'getSaldoclientes'])->name('cliente.saldo');
	Route::get('saldo/cliente/export', [ClienteController::class, 'getExcelSaldoclientes'])->name('cliente.saldo.export');

	Route::get('comentario/cliente/{cliente}', [ComentarioClienteController::class, 'create'])->name('comentario.create');
	Route::post('comentario/cliente/create', [ComentarioClienteController::class, 'store'])->name('comentario.store');
	Route::get('comentario/cliente/{comentario}/{cliente}', [ComentarioClienteController::class, 'edit'])->name('comentario.edit');
	Route::put('comentario/cliente/update/{comentario}/{cliente}', [ComentarioClienteController::class, 'update'])->name('comentario.update');
	Route::delete('comentario/cliente/delete/{comentario}', [ComentarioClienteController::class, 'destroy'] )->name('comentario.destroy');

	Route::resource('parametros', ParametroController::class);

	Route::resource('gateway', GatewayController::class);

	Route::resource('cbu', CbuController::class);

	Route::resource('CuentaCorriente', CuentaCorrienteController::class);

	Route::get('imputar/cliente/{clienteId}', [ImputarController::class, 'imputarAutomatico'])->name('imputar.cliente');
	Route::get('imputar/desimputar/pago/{idImputacion}', [ImputarController::class, 'desimputador'])->name('desimputar.pago');
	Route::get('imputar/lista/cliente/{cliente}', [ImputarController::class, 'imputarIndividual'])->name('imputar.cliente.recibos');
	Route::get('imputar/todo', [ImputarController::class, 'imputarTodo'])->name('imputar.todo');

	Route::get('credicard/{id}', [GatewayApiController::class, 'show']);
});
Route::get('/', [App\Http\Controllers\HomeController::class, 'index']);

app/Models/Unidad.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Kyslik\ColumnSortable\Sortable;

class Unidad extends Model
{
	use HasFactory, Sortable;
	protected $table = 'unidades', $fillable = ['nombre', 'hotel', 'capacidad', 'capacidad_maxima'];
	public $timestamps = false;


	public function hotelR()
	{
		return $this->belongsTo(Hotel::class, 'hotel', 'id');
	}
	public function clientes()
	{
		return $this->belongsToMany(Cliente::class, 'unidades_por_cliente', 'unidad', 'cliente', 'id', 'id')->withPivot(['temporada']);
	}
	public function temporadas()
	{
		return $this->belongsToMany(Temporada::class, 'unidades_por_cliente', 'unidad', 'temporada', 'id', 'id')->withPivot(['temporada']);
	}

	public function precioAnual()
	{
		return $this->hasMany(PrecioTemporadaAnio::class);
	}

	public function unidadPorCliente()
	{
		return $this->hasMany(UnidadPorCliente::class, 'unidad');
	}
}

app/Http/Controllers/UnidadController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StoreUnidadRequest;
use App\Http\Requests\UpdateUnidadRequest;
use App\Imports\HdcClienteUnidad;
use App\Imports\HdsClienteUnidadImport;
use App\Imports\UnidadImport;
use App\Models\Hotel;
use App\Models\Unidad;
use Illuminate\Http\Request;
use Maatwebsite\Excel\Facades\Excel;
use Illuminate\Support\Facades\Storage;

class UnidadController extends Controller
{
	/**
	 * Display a listing of the resource.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function index()
	{
		/* viejos */
		/* Excel::import(new HdcClienteUnidad ,Storage::path('/public/aux_unidad.xlsx')); */
		/* Excel::import(new HdsClienteUnidadImport ,Storage::path('/public/cliente-unidad-hds1.xlsx')); */
		/* Excel::import(new HdsClienteUnidadImport ,Storage::path('/public/cliente-unidad-hds2.xlsx')); */
		/* Excel::import(new HdcClienteUnidad ,Storage::path('/public/cliente-unidad-hdc.xlsx')); */

		/* nuevos */
		/* Excel::import(new HdcClienteUnidad ,Storage::path('/public/cliente-unidad-hdc-sept.xlsx')); */
		/* Excel::import(new HdsClienteUnidadImport ,Storage::path('/public/cliente-unidad-hds1-sept.xlsx')); */
		/* Excel::import(new HdsClienteUnidadImport ,Storage::path('/public/cliente-unidad-hds2-sept.xlsx')); */
		$unidades = Unidad::Sortable()->orderBy('nombre')->paginate(10);
		return view('unidad.index', compact('unidades'));
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function create()
	{
		$hotels = Hotel::orderBy('nombre', 'asc')->get();
		return view('unidad.store', compact('hotels'));
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @param  \Illuminate\Http\Request  $request
	 * @return \Illuminate\Http\Response
	 */
	public function store(StoreUnidadRequest $request)
	{
		$unidad = Unidad::create($request->all());
		$type = 'danger';
		$msg= 'Hubo un error con la creacion, por favor intente nuevamente o contacte directamente al administrador.';
		if ($unidad) {
			$type = 'success';
			$msg = 'Se ha creado correctamente la unidad '.$unidad->nombre.' .';
		}
		return redirect()->route('unidad.index')->with($type, $msg);
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return \Illuminate\Http\Response
	 */
	public function show(Unidad $unidad)
	{
		dd($unidad->toArray(), $unidad->json());
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return \Illuminate\Http\Response
	 */
	public function edit(Unidad $unidad)
	{
		$hotels = Hotel::orderBy('nombre', 'asc')->get();
		return view('unidad.update', compact('unidad', 'hotels'));
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  \Illuminate\Http\Request  $request
	 * @param  int  $id
	 * @return \Illuminate\Http\Response
	 */
	public function update(UpdateUnidadRequest $request, Unidad $unidad)
	{
		$created = $unidad->update($request->all());
		$type = 'danger';
		$msg= 'Hubo un error con la actualizacion, por favor intente nuevamente o contacte directamente al administrador.';
		if ($created) {
			$type = 'success';
			$msg = 'Se ha actualizado correctamente la unidad '.$unidad->nombre.' .';
		}
		return redirect()->route('unidad.index')->with($type, $msg);
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return \Illuminate\Http\Response
	 */
	public function destroy(Unidad $unidad)
	{
		//
	}
}

resources/views/unidad/index.blade.php
@extends('layouts.layout')
@section('title', 'Unidades')
@section('content')
    @if ($message = Session::get('success'))
        <div class="row justify-content-center">
            <div class=" col-6  mt-2 alert alert-success">
                <p>{{ $message }}</p>
            </div>
        </div>
    @endif
	<div class="row h-120-px align-items-center justify-content-between">
		<div class="col p-0 d-flex align-items-center gap-title">
			<h1 class="title-clubinn"> Unidad</h1>
		</div>
		<div class="col-8 col-xl-2 p-0 d-flex justify-content-end">
			<a href="{{ route('unidad.create') }}" type="button"
				class="btn btn-block btn-clubinn-blue clubinn-blue-color">Crear Unidad</a>
		</div>
    </div>

    <div class="row">
        <div class="col-12  p-0 table-responsive">
            @if ($unidades->isEmpty())
                <p class="lead">No existen unidades.</p>
            @else
                <table class="table table-bordered table-clubinn">
                    <thead>
                        <th scope="col" class="text-nowrap">@sortablelink('nombre', 'Nombre', [],  ['class' => ' clubinn-th-text'])</th>
                        <th scope="col"  class="text-nowrap">@sortablelink('capacidad', 'Capacidad', [],  ['class' => ' clubinn-th-text'])</th>
                        <th scope="col"  class="text-nowrap">@sortablelink('capacidad_maxima', 'Capacidad maxima', [],  ['class' => ' clubinn-th-text'])</th>
                        <th scope="col" class="text-nowrap">@sortablelink('hotel', 'Hotel', [],  ['class' => ' clubinn-th-text'])</th>
                        <th scope="col" class="text-nowrap"></th>
                    </thead>
                    <tbody>
                        @foreach ($unidades as $unidad)
                            <tr>
                                <td class="text-gergal-color">{{ $unidad->nombre }}</td>
                                <td class="text-gergal-color">{{ $unidad->capacidad }}</td>
                                <td class="text-gergal-color">{{ $unidad->capacidad_maxima }}</td>
                                <td class="text-gergal-color">{{ $unidad->hotelR->nombre }}</td>

                                <td>
                                    @can('unidad-edit')
                                        <a href="{{ route('unidad.edit', $unidad->id) }}" type="button"
                                            class="btn btn-outline-primary btn-sm  my-1"> <i class="fas fa-edit"></i></a>
                                    @endcan
                                    @can('unidad-delete')
                                        <form style="display: inline-block;" name="form-delete" action="{{ route('unidad.destroy', $unidad->id) }}"
                                            method="POST">
                                            @csrf
                                            @method('DELETE')
                                            <button type="submit" class="btn btn-outline-danger btn-sm" disabled><i
                                                    class="fas fa-trash-alt"></i></button>
                                        </form>
                                    @endcan

                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>

            @endif
            {{ method_exists($unidades, 'appends') ? $unidades->appends(\Request::except('page'))->render() : '' }}

        </div>
    </div>
@endsection

resources/views/unidad/store.blade.php
@extends('partials.form.form')

@section('form-title', 'Unidad')
@section('form-route', route('unidad.store'))
@section('form-content')
    <div class="form-group row">
        <div class="col-md-12 px-5">
            <input id="nombre" placeholder="Nombre" type="text"
                class="form-control @error('nombre') is-invalid @enderror" name="nombre"
                value="{{ old('nombre') }}">
            @error('nombre')
                <span class="invalid-feedback" style="background-color: red;
                               color: white;
                               margin-top: 0;" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
            @enderror
        </div>
    </div>
	<div class="form-group row">
        <div class="col-md-12 px-5">
            <input id="capacidad" placeholder="Capacidad" type="text"
                class="form-control @error('capacidad') is-invalid @enderror" name="capacidad"
                value="{{ old('capacidad') }}">
            @error('capacidad')
                <span class="invalid-feedback" style="background-color: red;
                               color: white;
                               margin-top: 0;" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
            @enderror
        </div>
    </div>
	<div class="form-group row">
        <div class="col-md-12 px-5">
            <input id="capacidad_maxima" placeholder="Capacidad maxima" type="text"
                class="form-control @error('capacidad_maxima') is-invalid @enderror" name="capacidad_maxima"
                value="{{ old('capacidad_maxima') }}">
            @error('capacidad_maxima')
                <span class="invalid-feedback" style="background-color: red;
                               color: white;
                               margin-top: 0;" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
            @enderror
        </div>
    </div>

    <div class="form-group row">
        <div class="col-md-12 px-5">
            <select class="form-control  @error('hotel') is-invalid @enderror" id="hotel" name="hotel" placeholder="hotel">
                <option selected disabled>-- Seleccione hotel --</option>
                @foreach ($hotels as $hotel)
                    <option value="{{ $hotel->id }}" {{ old('hotel') == $hotel->id ? 'selected' : ''}}>{{ $hotel->nombre }}</option>
                @endforeach
            </select>
            @error('hotel')
                <span class="invalid-feedback" style="background-color: red;
                   color: white;
                   margin-top: 0;" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
            @enderror
        </div>
    </div>
    <div class="form-group row mb-5">
        <div class="col-md-8 offset-4">
            <button type="submit" class="btn btn-success">
                Crear
            </button>
        </div>
    </div>
@endsection

resources/views/unidad/update.blade.php
@extends('partials.form.form')

@section('form-title', 'Unidad ')
@section('form-route', route('unidad.update', $unidad->id))
@section('form-content')
    @method('PUT')
	<div class="form-group row">
        <div class="col-md-12 px-5">
            <input id="nombre" placeholder="Nombre" type="text"
                class="form-control @error('nombre') is-invalid @enderror" name="nombre"
                value="{{ old('nombre', $unidad->nombre) }}">
            @error('nombre')
                <span class="invalid-feedback" style="background-color: red;
                               color: white;
                               margin-top: 0;" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
            @enderror
        </div>
    </div>
	<div class="form-group row">
        <div class="col-md-12 px-5">
            <input id="capacidad" placeholder="Capacidad" type="text"
                class="form-control @error('capacidad') is-invalid @enderror" name="capacidad"
                value="{{ old('capacidad', $unidad->capacidad) }}">
            @error('capacidad')
                <span class="invalid-feedback" style="background-color: red;
                               color: white;
                               margin-top: 0;" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
            @enderror
        </div>
    </div>
	<div class="form-group row">
        <div class="col-md-12 px-5">
            <input id="capacidad_maxima" placeholder="Capacidad maxima" type="text"
                class="form-control @error('capacidad_maxima') is-invalid @enderror" name="capacidad_maxima"
                value="{{ old('capacidad_maxima', $unidad->capacidad_maxima) }}">
            @error('capacidad_maxima')
                <span class="invalid-feedback" style="background-color: red;
                               color: white;
                               margin-top: 0;" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
            @enderror
        </div>
    </div>

    <div class="form-group row">
        <div class="col-md-12 px-5">
            <select class="form-control  @error('hotel') is-invalid @enderror" id="hotel" name="hotel" placeholder="hotel">
                <option selected disabled>-- Seleccione hotel --</option>
                @foreach ($hotels as $hotel)
                    <option value="{{ $hotel->id }}" {{ old('hotel',$unidad->hotel) == $hotel->id ? 'selected' : ''}}>{{ $hotel->nombre }}</option>
                @endforeach
            </select>
            @error('hotel')
                <span class="invalid-feedback" style="background-color: red;
                   color: white;
                   margin-top: 0;" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
            @enderror
        </div>
    </div>
    <div class="form-group row mb-5">
        <div class="col-md-8 offset-4">
            <button type="submit" class="btn btn-success">
                Actualizar unidad
            </button>
        </div>
    </div>
@endsection