routes/web.php
<?php

use App\Http\Controllers\api\GatewayApiController;
use App\Http\Controllers\CbuController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ClienteController;
use App\Http\Controllers\ComentarioClienteController;
use App\Http\Controllers\ConsultaController;
use App\Http\Controllers\CuentaCorrienteController;
use App\Http\Controllers\ExpensaController;
use App\Http\Controllers\GatewayController;
use App\Http\Controllers\HotelController;
use App\Http\Controllers\ImputarController;
use App\Http\Controllers\ParametroController;
use App\Http\Controllers\ReciboController;
use App\Http\Controllers\SemanaUsoController;
use App\Http\Controllers\TemporadaController;
use App\Http\Controllers\UnidadController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();
Route::get('cliente/reset/{token}', [ClienteController::class, 'resetPasswordForm'])->name('cliente.reset.get');
Route::put('cliente/reset/{cliente}', [ClienteController::class, 'resetPassword'])->name('cliente.reset.update');
Route::get('recibos/pdf/{recibo}', [ReciboController::class, 'getReciboPdf'])->name('recibos.pdf');
Route::get('recibos/pdf/{recibo}/export', [ReciboController::class, 'getPdfExportRecibo'])->name('recibos.pdf.export');
Route::get('hotel/calendario/{hotel}', [HotelController::class, 'getCalendario'])->name('hotel.calendario');

Route::middleware(['auth'])->group(function () {
	Route::get('cliente/saldo/especifico', [ClienteController::class, 'getClienteComposicionSaldoTodo'])->name('cliente.saldo.compuesto.todos');
	Route::get('cliente/saldo/composicion/{clienteId}', [ClienteController::class, 'getClienteComposicionSaldo'])->name('cliente.saldo.compuesto');
	Route::get('cliente/exportar/excel/{filter?}', [ClienteController::class ,'exportClientesExcel'])->name('cliente.exportar.contratos');
	Route::resource('cliente', ClienteController::class);

	Route::resource('temporada', TemporadaController::class);

	Route::resource('hotel', HotelController::class);

	Route::resource('unidad', UnidadController::class);

	Route::resource('consultas', ConsultaController::class);

	Route::resource('recibos', ReciboController::class);
	Route::get('recibo/export', [ReciboController::class, 'getReciboExport'])->name('recibos.export');

	Route::get('expensas/choose', [ExpensaController::class, 'chooseTempAndHotel'])->name('expensas.choose');
	Route::post('expensas/unidad', [ExpensaController::class, 'createPricesToUnidad'])->name('expensas.unidad');
	Route::get('expensas/clientes/{temporada}/{anio}/{fecha}/{fecha_vencimiento}', [ExpensaController::class, 'generateExpensas'])->name('expensas.clientes');
	Route::resource('expensas', ExpensaController::class);
	Route::get('expensas/unica/cliente', [ExpensaController::class, 'createUniqueExpensa'])->name('expensa.unica');
	Route::post('expensas/unica/cliente', [ExpensaController::class, 'createUniqueExpensaStore'])->name('expensa.unica.store');

	Route::get('usos/excel/download', [SemanaUsoController::class, 'exportToExcel'])->name('usos.excel.download');
	Route::resource('usos', SemanaUsoController::class);

	Route::get('saldo/cliente', [ClienteController::class, 'getSaldoclientes'])->name('cliente.saldo');
	Route::get('saldo/cliente/export', [ClienteController::class, 'getExcelSaldoclientes'])->name('cliente.saldo.export');

	Route::get('comentario/cliente/{cliente}', [ComentarioClienteController::class, 'create'])->name('comentario.create');
	Route::post('comentario/cliente/create', [ComentarioClienteController::class, 'store'])->name('comentario.store');
	Route::get('comentario/cliente/{comentario}/{cliente}', [ComentarioClienteController::class, 'edit'])->name('comentario.edit');
	Route::put('comentario/cliente/update/{comentario}/{cliente}', [ComentarioClienteController::class, 'update'])->name('comentario.update');
	Route::delete('comentario/cliente/delete/{comentario}', [ComentarioClienteController::class, 'destroy'] )->name('comentario.destroy');

	Route::resource('parametros', ParametroController::class);

	Route::resource('gateway', GatewayController::class);

	Route::resource('cbu', CbuController::class);

	Route::resource('CuentaCorriente', CuentaCorrienteController::class);

	Route::get('imputar/cliente/{clienteId}', [ImputarController::class, 'imputarAutomatico'])->name('imputar.cliente');
	Route::get('imputar/desimputar/pago/{idImputacion}', [ImputarController::class, 'desimputador'])->name('desimputar.pago');
	Route::get('imputar/lista/cliente/{cliente}', [ImputarController::class, 'imputarIndividual'])->name('imputar.cliente.recibos');
	Route::get('imputar/todo', [ImputarController::class, 'imputarTodo'])->name('imputar.todo');

	Route::get('credicard/{id}', [GatewayApiController::class, 'show']);
});
Route::get('/', [App\Http\Controllers\HomeController::class, 'index']);

app/Models/Cbu.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Kyslik\ColumnSortable\Sortable;

class Cbu extends Model
{
    use HasFactory, Sortable;
	protected $table = 'cbus';
	protected $fillable = [
		'banco',
		'titular',
		'tipo_cuenta',
		'nro_cuenta',
		'cbu',
		'cuil',
	];
}

app/Http/Controllers/CbuController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StoreCbuRequest;
use App\Models\Cbu;
use Illuminate\Http\Request;

class CbuController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
		$filter = $request->filter;
        $cbus  = Cbu::sortable()->orderBy('banco', 'asc')
			->when($filter , function ($query) use($filter ){
				return $query->where('banco', 'like', '%'.$filter  . '%')
					->orWhere('cbu', 'like', '%'.$filter . '%')
					->orWhere('nro_cuenta', 'like', '%'.$filter  . '%')
					->orWhere('tipo_cuenta', 'like', '%'.$filter  . '%')
					->orWhere('titular', 'like', '%'.$filter  . '%')
					;
			})
			->get();


		return view('cbu.index', compact('cbus', 'filter'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
		$tipo_cuentas = [ ['nombre' => 'cuenta corriente']];
        return view('cbu.store', compact('tipo_cuentas') );
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreCbuRequest $request)
    {
       $cbu = Cbu::create($request->all());

	   return redirect()->route('cbu.index')->with('success','Se ha creado la cbu '.$cbu->cbu.'.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Cbu $cbu)
    {
		$tipo_cuentas = [ ['nombre' => 'cuenta corriente']];

       return view('cbu.update', compact('cbu', 'tipo_cuentas'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(StoreCbuRequest $request, Cbu $cbu)
    {
        $cbu->update($request->all());
		return redirect()->route('cbu.index')->with('success','Se ha actualizado la cbu '.$cbu->cbu.'.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Cbu $cbu)
    {
        $cbu->delete();
		return redirect()->route('cbu.index')->with('success','Se ha borrado la cbu '.$cbu->cbu.'.');

    }
}

resources/views/cbu/index.blade.php
@extends('layouts.layout')
@section('title', 'Cbu')
@section('content')
    @if ($message = Session::get('success'))
        <div class="row justify-content-center">
            <div class=" col-6  mt-2 alert alert-success">
                <p>{{ $message }}</p>
            </div>
        </div>
    @endif
    <div class="row h-120-px align-items-center justify-content-between">
        <div class="col p-0 d-flex align-items-center gap-title">
            <i class="fas fa-user-circle fa-3x" style="color: #e8a02f !important; "></i>
            <h1 class="title-clubinn">Cbu</h1>
        </div>
        <div class="col-12 col-xl-8 p-0 d-flex justify-content-end">
            <form class="col-8 input-group" action="" method="get">
                <input placeholder="Filtrar por banco, cbu, tipo de cuenta o titular." name="filter" class="form-control"
                    type="text" value="{{ old('filter', $filter) }}">
                <div class="input-group-append"><button class="btn btn-success " type="submit">Filtrar</button></div>
            </form>
            <div class="col">
                <a href="{{ route('cbu.create') }}" type="button"
                    class="btn btn-block btn-clubinn-blue clubinn-blue-color"> Crear cbu</a>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-12  p-0 table-responsive">
            @if ($cbus->isEmpty())
                <p class="lead">No existen cbu cargado.</p>
            @else
                <table class="table table-bordered table-clubinn">
                    <thead>
                        <th scope="col" class="text-nowrap">@sortablelink('banco', 'Banco', [], ['class' => '
                            clubinn-th-text'])</th>
                        <th scope="col" class="text-nowrap">@sortablelink('tipo_cuenta', 'Tipo de cuenta', [], ['class'
                            => '
                            clubinn-th-text'])</th>
                        <th scope="col" class="text-nowrap">@sortablelink('cbu', 'Cbu', [], ['class' => '
                            clubinn-th-text'])</th>
                        <th scope="col" class="text-nowrap">@sortablelink('nro_cuenta', 'Numero de cuenta', [], ['class'
                            => '
                            clubinn-th-text'])</th>
                        <th scope="col" class="text-nowrap">@sortablelink('titular', 'Titular', [], ['class' => '
                            clubinn-th-text'])</th>
                        <th scope="col" class="text-nowrap"></th>
                    </thead>
                    <tbody>

                        @foreach ($cbus as $cbu)
                            <tr>
                                <td class="text-gergal-color text-white">{{ $cbu->banco }}</td>
                                <td class="text-gergal-color text-white">{{ $cbu->tipo_cuenta }}</td>
                                <td class="text-gergal-color text-white">{{ $cbu->cbu }}</td>
                                <td class="text-gergal-color text-white">{{ $cbu->nro_cuenta }}</td>
                                <td class="text-gergal-color text-white">{{ $cbu->titular }}</td>

                                <td>


                                    @can('cbu-edit')
                                        <a href="{{ route('cbu.edit', $cbu->id) }}" type="button"
                                            class="btn btn-outline-primary btn-sm  my-1"> <i class="fas fa-edit"></i></a>
                                    @endcan
                                    @can('cbu-delete')
                                        <form style="display: inline-block;" name="form-delete"
                                            action="{{ route('cbu.destroy', $cbu->id) }}" method="POST">
                                            @csrf
                                            @method('DELETE')
                                            <button type="submit" class="btn btn-outline-danger btn-sm" disabled><i
                                                    class="fas fa-trash-alt"></i></button>
                                        </form>
                                    @endcan

                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>

            @endif
            {{ method_exists($cbus, 'appends') ? $cbus->appends(\Request::except('page'))->render() : '' }}

        </div>
    </div>
    <script src="{{ asset('js/delete.js') }}"></script>
    <script type="text/javascript">

    </script>
@endsection

resources/views/cbu/store.blade.php
@extends('partials.form.form')

@section('form-title', 'Cbu')
@section('form-route', route('cbu.store'))
@section('form-content')
    <div class="form-group row">
        <div class="col-md-12 px-5 input-group ">
            <div class="input-group-prepend">
                <span class="input-group-text" id="basic-addon1">Banco</span>
            </div>
            <input id="banco" placeholder="Banco" type="text"
                class="form-control @error('banco') is-invalid @enderror" name="banco" value="{{ old('banco') }}">
            @error('banco')
                <span class="invalid-feedback"
                    style="background-color: red;
                                                                                                                       color: white;
                                                                                                                       margin-top: 0;" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
            @enderror
        </div>
    </div>

    <div class="form-group row">
        <div class="col-md-12 px-5 input-group ">
            <div class="input-group-prepend">
                <span class="input-group-text" id="basic-addon1">Titular</span>
            </div>
            <input id="titular" placeholder="titular" type="text"
                class="form-control @error('titular') is-invalid @enderror" name="titular" value="{{ old('titular') }}">
            @error('titular')
                <span class="invalid-feedback"
                    style="background-color: red;
                                                                                                                       color: white;
                                                                                                                       margin-top: 0;" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
            @enderror
        </div>
    </div>
	<div class="form-group row">
        <div class="col-md-12 px-5 input-group ">
            <div class="input-group-prepend">
                <span class="input-group-text" id="basic-addon1">Cuil</span>
            </div>
            <input id="cuil" placeholder="cuil" type="text"
                class="form-control @error('cuil') is-invalid @enderror" name="cuil" value="{{ old('cuil') }}">
            @error('cuil')
                <span class="invalid-feedback"
                    style="background-color: red;
                                                                                                                       color: white;
                                                                                                                       margin-top: 0;" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
            @enderror
        </div>
    </div>
	<div class="form-group row">
        <div class="col-md-12 px-5 input-group ">
            <div class="input-group-prepend">
                <span class="input-group-text" id="basic-addon1">Numero de cuenta</span>
            </div>
            <input id="nro_cuenta" placeholder="Nro de cuenta" type="text"
                class="form-control @error('nro_cuenta') is-invalid @enderror" name="nro_cuenta" value="{{ old('nro_cuenta') }}">
            @error('nro_cuenta')
                <span class="invalid-feedback"
                    style="background-color: red;
                                                                                                                       color: white;
                                                                                                                       margin-top: 0;" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
            @enderror
        </div>
    </div>
	<div class="form-group row">
        <div class="col-md-12 px-5 input-group ">
            <div class="input-group-prepend">
                <span class="input-group-text" id="basic-addon1">Cbu</span>
            </div>
            <input id="cbu" placeholder="Cbu" type="text"
                class="form-control @error('cbu') is-invalid @enderror" name="cbu" value="{{ old('cbu') }}">
            @error('cbu')
                <span class="invalid-feedback"
                    style="background-color: red;
                                                                                                                       color: white;
                                                                                                                       margin-top: 0;" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
            @enderror
        </div>
    </div>

    <div class="form-group row" >
        <div class="col-md-12 px-5">
            <select class="form-control  @error('tipo_cuenta') is-invalid @enderror" id="tipo_cuenta"
                name="tipo_cuenta" placeholder="">
                <option selected disabled>-- Seleccione tipo de cuenta --</option>
                @foreach ($tipo_cuentas as $tipo_cuenta)
                    <option value="{{ $tipo_cuenta['nombre'] }}"
                        {{ old('tipo_cuenta') == $tipo_cuenta['nombre'] ? 'selected' : '' }}>
                        {{ $tipo_cuenta['nombre'] }}</option>
                @endforeach
            </select>
            @error('tipo_cuenta')
                <span class="invalid-feedback" style="background-color: red;
                                                                                                   color: white;
                                                                                                   margin-top: 0;"
                    role="alert">
                    <strong>{{ $message }}</strong>
                </span>
            @enderror
        </div>
    </div>



    <div class="form-group row mb-5">
        <div class="col-md-8 offset-4">
            <button type="submit" class="btn btn-success">
                Crear Cbu
            </button>
        </div>
    </div>


@endsection

<script type="text/javascript">

</script>

resources/views/cbu/update.blade.php
@extends('partials.form.form')

@section('form-title', 'Cbu')
@section('form-route', route('cbu.update', $cbu->id))
@section('form-content')
    @method('PUT')
	<div class="form-group row">
        <div class="col-md-12 px-5 input-group ">
            <div class="input-group-prepend">
                <span class="input-group-text" id="basic-addon1">Banco</span>
            </div>
            <input id="banco" placeholder="Banco" type="text"
                class="form-control @error('banco') is-invalid @enderror" name="banco" value="{{ old('banco', $cbu->banco) }}">
            @error('banco')
                <span class="invalid-feedback"
                    style="background-color: red;
                                                                                                                       color: white;
                                                                                                                       margin-top: 0;" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
            @enderror
        </div>
    </div>

    <div class="form-group row">
        <div class="col-md-12 px-5 input-group ">
            <div class="input-group-prepend">
                <span class="input-group-text" id="basic-addon1">Titular</span>
            </div>
            <input id="titular" placeholder="titular" type="text"
                class="form-control @error('titular') is-invalid @enderror" name="titular" value="{{ old('titular', $cbu->titular) }}">
            @error('titular')
                <span class="invalid-feedback"
                    style="background-color: red;
                                                                                                                       color: white;
                                                                                                                       margin-top: 0;" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
            @enderror
        </div>
    </div>
	<div class="form-group row">
        <div class="col-md-12 px-5 input-group ">
            <div class="input-group-prepend">
                <span class="input-group-text" id="basic-addon1">Cuil</span>
            </div>
            <input id="cuil" placeholder="cuil" type="text"
                class="form-control @error('cuil') is-invalid @enderror" name="cuil" value="{{ old('cuil', $cbu->cuil) }}">
            @error('cuil')
                <span class="invalid-feedback"
                    style="background-color: red;
                                                                                                                       color: white;
                                                                                                                       margin-top: 0;" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
            @enderror
        </div>
    </div>
	<div class="form-group row">
        <div class="col-md-12 px-5 input-group ">
            <div class="input-group-prepend">
                <span class="input-group-text" id="basic-addon1">Numero de cuenta</span>
            </div>
            <input id="nro_cuenta" placeholder="Nro de cuenta" type="text"
                class="form-control @error('nro_cuenta') is-invalid @enderror" name="nro_cuenta" value="{{ old('nro_cuenta',$cbu->nro_cuenta) }}">
            @error('nro_cuenta')
                <span class="invalid-feedback"
                    style="background-color: red;
                                                                                                                       color: white;
                                                                                                                       margin-top: 0;" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
            @enderror
        </div>
    </div>
	<div class="form-group row">
        <div class="col-md-12 px-5 input-group ">
            <div class="input-group-prepend">
                <span class="input-group-text" id="basic-addon1">Cbu</span>
            </div>
            <input id="cbu" placeholder="Cbu" type="text"
                class="form-control @error('cbu') is-invalid @enderror" name="cbu" value="{{ old('cbu', $cbu->cbu) }}">
            @error('cbu')
                <span class="invalid-feedback"
                    style="background-color: red;
                                                                                                                       color: white;
                                                                                                                       margin-top: 0;" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
            @enderror
        </div>
    </div>

    <div class="form-group row" >
        <div class="col-md-12 px-5">
            <select class="form-control  @error('tipo_cuenta') is-invalid @enderror" id="tipo_cuenta"
                name="tipo_cuenta" placeholder="">
                <option selected disabled>-- Seleccione tipo de cuenta --</option>
                @foreach ($tipo_cuentas as $tipo_cuenta)
                    <option value="{{ $tipo_cuenta['nombre'] }}"
                        {{ old('tipo_cuenta', $cbu->tipo_cuenta) == $tipo_cuenta['nombre'] ? 'selected' : '' }}>
                        {{ $tipo_cuenta['nombre'] }}</option>
                @endforeach
            </select>
            @error('tipo_cuenta')
                <span class="invalid-feedback" style="background-color: red;
                                                                                                   color: white;
                                                                                                   margin-top: 0;"
                    role="alert">
                    <strong>{{ $message }}</strong>
                </span>
            @enderror
        </div>
    </div>
    <div class="form-group row mb-5">
        <div class="col-md-8 offset-4">
            <button type="submit" class="btn btn-success">
                Actualizar Cbu
            </button>
        </div>
    </div>
@endsection