routes/web.php
<?php

use App\Http\Controllers\api\GatewayApiController;
use App\Http\Controllers\CbuController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ClienteController;
use App\Http\Controllers\ComentarioClienteController;
use App\Http\Controllers\ConsultaController;
use App\Http\Controllers\CuentaCorrienteController;
use App\Http\Controllers\ExpensaController;
use App\Http\Controllers\GatewayController;
use App\Http\Controllers\HotelController;
use App\Http\Controllers\ImputarController;
use App\Http\Controllers\ParametroController;
use App\Http\Controllers\ReciboController;
use App\Http\Controllers\SemanaUsoController;
use App\Http\Controllers\TemporadaController;
use App\Http\Controllers\UnidadController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();
Route::get('cliente/reset/{token}', [ClienteController::class, 'resetPasswordForm'])->name('cliente.reset.get');
Route::put('cliente/reset/{cliente}', [ClienteController::class, 'resetPassword'])->name('cliente.reset.update');
Route::get('recibos/pdf/{recibo}', [ReciboController::class, 'getReciboPdf'])->name('recibos.pdf');
Route::get('recibos/pdf/{recibo}/export', [ReciboController::class, 'getPdfExportRecibo'])->name('recibos.pdf.export');
Route::get('hotel/calendario/{hotel}', [HotelController::class, 'getCalendario'])->name('hotel.calendario');

Route::middleware(['auth'])->group(function () {
	Route::get('cliente/saldo/especifico', [ClienteController::class, 'getClienteComposicionSaldoTodo'])->name('cliente.saldo.compuesto.todos');
	Route::get('cliente/saldo/composicion/{clienteId}', [ClienteController::class, 'getClienteComposicionSaldo'])->name('cliente.saldo.compuesto');
	Route::get('cliente/exportar/excel/{filter?}', [ClienteController::class ,'exportClientesExcel'])->name('cliente.exportar.contratos');
	Route::resource('cliente', ClienteController::class);

	Route::resource('temporada', TemporadaController::class);

	Route::resource('hotel', HotelController::class);

	Route::resource('unidad', UnidadController::class);

	Route::resource('consultas', ConsultaController::class);

	Route::resource('recibos', ReciboController::class);
	Route::get('recibo/export', [ReciboController::class, 'getReciboExport'])->name('recibos.export');

	Route::get('expensas/choose', [ExpensaController::class, 'chooseTempAndHotel'])->name('expensas.choose');
	Route::post('expensas/unidad', [ExpensaController::class, 'createPricesToUnidad'])->name('expensas.unidad');
	Route::get('expensas/clientes/{temporada}/{anio}/{fecha}/{fecha_vencimiento}', [ExpensaController::class, 'generateExpensas'])->name('expensas.clientes');
	Route::resource('expensas', ExpensaController::class);
	Route::get('expensas/unica/cliente', [ExpensaController::class, 'createUniqueExpensa'])->name('expensa.unica');
	Route::post('expensas/unica/cliente', [ExpensaController::class, 'createUniqueExpensaStore'])->name('expensa.unica.store');

	Route::get('usos/excel/download', [SemanaUsoController::class, 'exportToExcel'])->name('usos.excel.download');
	Route::resource('usos', SemanaUsoController::class);

	Route::get('saldo/cliente', [ClienteController::class, 'getSaldoclientes'])->name('cliente.saldo');
	Route::get('saldo/cliente/export', [ClienteController::class, 'getExcelSaldoclientes'])->name('cliente.saldo.export');

	Route::get('comentario/cliente/{cliente}', [ComentarioClienteController::class, 'create'])->name('comentario.create');
	Route::post('comentario/cliente/create', [ComentarioClienteController::class, 'store'])->name('comentario.store');
	Route::get('comentario/cliente/{comentario}/{cliente}', [ComentarioClienteController::class, 'edit'])->name('comentario.edit');
	Route::put('comentario/cliente/update/{comentario}/{cliente}', [ComentarioClienteController::class, 'update'])->name('comentario.update');
	Route::delete('comentario/cliente/delete/{comentario}', [ComentarioClienteController::class, 'destroy'] )->name('comentario.destroy');

	Route::resource('parametros', ParametroController::class);

	Route::resource('gateway', GatewayController::class);

	Route::resource('cbu', CbuController::class);

	Route::resource('CuentaCorriente', CuentaCorrienteController::class);

	Route::get('imputar/cliente/{clienteId}', [ImputarController::class, 'imputarAutomatico'])->name('imputar.cliente');
	Route::get('imputar/desimputar/pago/{idImputacion}', [ImputarController::class, 'desimputador'])->name('desimputar.pago');
	Route::get('imputar/lista/cliente/{cliente}', [ImputarController::class, 'imputarIndividual'])->name('imputar.cliente.recibos');
	Route::get('imputar/todo', [ImputarController::class, 'imputarTodo'])->name('imputar.todo');

	Route::get('credicard/{id}', [GatewayApiController::class, 'show']);
});
Route::get('/', [App\Http\Controllers\HomeController::class, 'index']);

app/Models/Temporada.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Kyslik\ColumnSortable\Sortable;

class Temporada extends Model
{
    use HasFactory, Sortable;
    protected $table = 'temporadas', $fillable = ['identificacion', 'nombre', 'hotel', 'fraccionado'],
	$sortable = ['identificacion', 'nombre', 'hotel', 'fraccionado'];
    public $timestamps = false;

    public function hotelR(){
        return $this->belongsTo(Hotel::class, 'hotel', 'id');
    }
	public function semanas(){
		return $this->hasMany(SemanaTemporada::class);
	}
	public function unidadPorCliente(){
		return $this->hasMany(UnidadPorCliente::class, 'temporada');
	}
}

app/Http/Controllers/TemporadaController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StoreTemporadaRequest;
use App\Models\Hotel;
use App\Models\Temporada;
use Illuminate\Http\Request;

class TemporadaController extends Controller
{

	public function __construct(){
		$this->middleware('permission:temporada-list|temporada-create|temporada-edit|temporada-delete', ['only' => ['index','show']]);
		$this->middleware('permission:temporada-create', ['only' => ['create','store']]);
		$this->middleware('permission:temporada-edit', ['only' => ['edit','update']]);
		$this->middleware('permission:temporada-delete', ['only' => ['destroy']]);
	}
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
		$temporadas = Temporada::sortable()->orderBy('id', 'desc')->get();

		return view('temporada.index', compact('temporadas'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
		$hotels = Hotel::orderBy('nombre', 'asc')->get();

		return view('temporada.store', compact('hotels') );
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreTemporadaRequest $request)
    {
		$temporada = Temporada::create($request->all());
		$type = 'danger';
		$msg= 'Hubo un error con la creacion, por favor intente nuevamente o contacte directamente al administrador.';
		if ($temporada) {
			$type = 'success';
			$msg = 'Se ha creado correctamente la temporada '.$temporada->nombre.' .';
		}
		return redirect()->route('temporada.index')->with($type, $msg);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Temporada $temporada)
    {
		$hotels = Hotel::orderBy('nombre', 'asc')->get();

      return view('temporada.update', compact('temporada', 'hotels'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(StoreTemporadaRequest $request, Temporada $temporada)
    {
        $temporada->update($request->all());
		$type = 'danger';
		$msg= 'Hubo un error con la actualizacion, por favor intente nuevamente o contacte directamente al administrador.';
		if ($temporada) {
			$type = 'success';
			$msg = 'Se ha creado correctamente la temporada '.$temporada->nombre.' .';
		}
		return redirect()->route('temporada.index')->with($type, $msg);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/api/TemporadaController.php
<?php

namespace App\Http\Controllers\api;

use App\Http\Controllers\Controller;
use App\Models\Temporada;
use Illuminate\Http\Request;

class TemporadaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
	public function showByHotel($idHotel){
		$temporadas = Temporada::where('hotel', $idHotel)->orderBy('nombre', 'asc')->get();

		return response()->json(['status' => 'ok', 'data' => $temporadas]);
	}
	public function showBycliente($idCliente){
		$temporadas = Temporada::WhereHas('unidadPorCliente', function($query)use($idCliente){
			return $query->where('cliente', $idCliente);
		})->get();
		return response()->json(['status' => 'ok', 'data' => $temporadas]);
	}
}

resources/views/temporada/index.blade.php
@extends('layouts.layout')
@section('title', 'Temporada')
@section('content')
    @if ($message = Session::get('success'))
        <div class="row justify-content-center">
            <div class=" col-6  mt-2 alert alert-success">
                <p>{{ $message }}</p>
            </div>
        </div>
    @endif
	<div class="row h-120-px align-items-center justify-content-between">
		<div class="col p-0 d-flex align-items-center gap-title">
			<h1 class="title-clubinn"> Temporada</h1>
		</div>
		<div class="col-8 col-xl-2 p-0 d-flex justify-content-end">
			<a href="{{ route('temporada.create') }}" type="button"
				class="btn btn-block btn-clubinn-blue clubinn-blue-color">Crear temporada</a>
		</div>
    </div>

    <div class="row">
        <div class="col-12  p-0 table-responsive">
            @if ($temporadas->isEmpty())
                <p class="lead">No existen Temporadas.</p>
            @else
                <table class="table table-bordered table-clubinn">
                    <thead>
                        <th scope="col"  class="text-nowrap">@sortablelink('identificacion', 'Identificación', [],  ['class' => ' clubinn-th-text'])</th>
                        <th scope="col" class="text-nowrap">@sortablelink('nombre', 'Nombre', [],  ['class' => ' clubinn-th-text'])</th>
                        <th scope="col" class="text-nowrap">@sortablelink('hotel', 'Hotel', [],  ['class' => ' clubinn-th-text'])</th>
                        <th scope="col" class="text-nowrap"></th>
                    </thead>
                    <tbody>
                        @foreach ($temporadas as $temporada)
                            <tr>
                                <td class="text-gergal-color">{{ $temporada->identificacion }}</td>
                                <td class="text-gergal-color">{{ $temporada->nombre }}</td>
                                <td class="text-gergal-color">{{ $temporada->hotelR->nombre }}</td>

                                <td>
                                    @can('temporada-edit')
                                        <a href="{{ route('temporada.edit', $temporada->id) }}" type="button"
                                            class="btn btn-outline-primary btn-sm  my-1"> <i class="fas fa-edit"></i></a>
                                    @endcan
                                    @can('temporada-delete')
                                        <form style="display: inline-block;"  name="form-delete" action="{{ route('temporada.destroy', $temporada->id) }}"
                                            method="POST">
                                            @csrf
                                            @method('DELETE')
                                            <button type="submit" class="btn btn-outline-danger btn-sm" disabled><i
                                                    class="fas fa-trash-alt"></i></button>
                                        </form>
                                    @endcan

                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>

            @endif
            {{ method_exists($temporadas, 'appends') ? $temporadas->appends(\Request::except('page'))->render() : '' }}

        </div>
    </div>
@endsection

resources/views/temporada/store.blade.php
@extends('partials.form.form')

@section('form-title', 'Temporada')
@section('form-route', route('temporada.store'))
@section('form-content')
    <div class="form-group row">
        <div class="col-md-12 px-5">
            <input id="identificacion" placeholder="Identificacion" type="text"
                class="form-control @error('identificacion') is-invalid @enderror" name="identificacion"
                value="{{ old('identificacion') }}">
            @error('identificacion')
                <span class="invalid-feedback" style="background-color: red;
                               color: white;
                               margin-top: 0;" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
            @enderror
        </div>
    </div>
    <div class="form-group row">
        <div class="col-md-12 px-5">
            <input id="nombre" placeholder="Nombre" type="text" class="form-control @error('nombre') is-invalid @enderror"
                name="nombre" value="{{ old('nombre') }}" autofocus>
            @error('nombre')
                <span class="invalid-feedback" style="background-color: red;
                                color: white;
                                margin-top: 0;" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
            @enderror
        </div>
    </div>


    <div class="form-group row">
        <div class="col-md-12 px-5">
            <select class="form-control  @error('hotel') is-invalid @enderror" id="hotel" name="hotel" placeholder="hotel">
                <option selected disabled>-- Seleccione hotel --</option>
                @foreach ($hotels as $hotel)
                    <option value="{{ $hotel->id }}" {{ old('hotel') == $hotel->id ? 'selected' : ''}}>{{ $hotel->nombre }}</option>
                @endforeach
            </select>
            @error('hotel')
                <span class="invalid-feedback" style="background-color: red;
                   color: white;
                   margin-top: 0;" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
            @enderror
        </div>
    </div>
    <div class="form-group row mb-5">
        <div class="col-md-8 offset-4">
            <button type="submit" class="btn btn-success">
                Crear
            </button>
        </div>
    </div>
@endsection

resources/views/temporada/update.blade.php
@extends('partials.form.form')

@section('form-title', 'Temporada ')
@section('form-route', route('temporada.update', $temporada->id))
@section('form-content')
    @method('PUT')
    <div class="form-group row">
        <div class="col-md-12 px-5">
            <input id="identificacion" placeholder="Identificacion" type="text"
                class="form-control @error('identificacion') is-invalid @enderror" name="identificacion"
                value="{{ old('identificacion', $temporada->identificacion) }}">
            @error('identificacion')
                <span class="invalid-feedback" style="background-color: red;
              color: white;
              margin-top: 0;" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
            @enderror
        </div>
    </div>
    <div class="form-group row">
        <div class="col-md-12 px-5">
            <input id="nombre" placeholder="Nombre" type="text" class="form-control @error('nombre') is-invalid @enderror"
                name="nombre" value="{{ old('nombre', $temporada->nombre) }}" autofocus>
            @error('nombre')
                <span class="invalid-feedback" style="background-color: red;
               color: white;
               margin-top: 0;" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
            @enderror
        </div>
    </div>


    <div class="form-group row">
        <div class="col-md-12 px-5">
            <select class="form-control  @error('hotel') is-invalid @enderror" id="hotel" name="hotel" placeholder="hotel">
                <option selected disabled>-- Seleccione hotel --</option>
                @foreach ($hotels as $hotel)
                    <option value="{{ $hotel->id }}" {{ old('hotel', $temporada->hotel) == $hotel->id ? 'selected' : '' }}>
                        {{ $hotel->nombre }}</option>
                @endforeach
            </select>
            @error('hotel')
                <span class="invalid-feedback" style="background-color: red;
           color: white;
           margin-top: 0;" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
            @enderror
        </div>
    </div>
    <div class="form-group row mb-5">
        <div class="col-md-8 offset-4">
            <button type="submit" class="btn btn-success">
                Actualizar Temporada
            </button>
        </div>
    </div>
@endsection